/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-03-27 14:15:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manager2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fhead_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsx_005fautocompleter_0026_005fshowDownArrow_005fname_005flist_005fid_005fcssStyle_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsx_005fhead_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsx_005fautocompleter_0026_005fshowDownArrow_005fname_005flist_005fid_005fcssStyle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsx_005fhead_005fnobody.release();
    _005fjspx_005ftagPool_005fsx_005fautocompleter_0026_005fshowDownArrow_005fname_005flist_005fid_005fcssStyle_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      if (_jspx_meth_sx_005fhead_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Manager Form</title>\n");
      out.write("  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>\n");
      out.write("  <link type=\"text/css\" rel=\"Stylesheet\" href=\"http://ajax.microsoft.com/ajax/jquery.ui/1.8.6/themes/smoothness/jquery-ui.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"Css/style.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"Css/styleForLastpages.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<form >\n");
      out.write(" <button formaction=\"logOut\" type=\"submit\" id=\"logOut\">LogOut</button>\n");
      out.write("</form>\n");
      out.write("<div class=\"form\">\n");
      out.write("     <h1>Complaints Search Form</h1>\n");
      out.write("       <div id=\"signup\">\n");
      out.write("          <form action=\"manager1SearchResult\" method=\"post\" id=\"managerForm\">\n");
      out.write("           <div class=\"field-wrap\">\n");
      out.write("               <label style=\"margin-top:-40px;\">Customer Name</label>\n");
      out.write("               <br>\n");
      out.write("               <br>\n");
      out.write("              ");
      if (_jspx_meth_sx_005fautocompleter_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            </div>\n");
      out.write("     <br>\n");
      out.write("     <br>\n");
      out.write("         <div class=\"field-wrap\" style=\"margin-top:-15px;\">\n");
      out.write("         \n");
      out.write("            <input placeholder=\"Mobile Number\"type=\"text\" autocomplete=\"off\" id=\"mobileNumber\" name=\"mobileNumber\"/>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"field-wrap\" style=\"margin-top:-15px;\">\n");
      out.write("            <label style=\"margin-left:-10px;\">\n");
      out.write("             Complaints:From Date\n");
      out.write("            </label>\n");
      out.write("            <br>\n");
      out.write("            <br>\n");
      out.write("             <input type=\"text\" id=\"calendar\" autocomplete=\"off\" name=\"fromDate\"/>\n");
      out.write("           </div>\n");
      out.write("           <div class=\"field-wrap\" style=\"margin-top:-15px;\">\n");
      out.write("             <label style=\"margin-left:-10px;\">\n");
      out.write("               Complaints:To Date\n");
      out.write("             </label>\n");
      out.write("             <br>\n");
      out.write("             <br>\n");
      out.write("              <input type=\"text\" id=\"calendar1\" autocomplete=\"off\" name=\"toDate\"/>\n");
      out.write("            </div>\n");
      out.write("           <input type=\"text\" name=\"email\" value=\"");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("\" style=\"display:none;\"/>\n");
      out.write("          <button type=\"submit\" class=\"button button-block\" id=\"search\">Search</button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("</div> <!-- /form -->\n");
      out.write("<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\n");
      out.write("<script src=\"Js/manager.js\"></script>\n");
      out.write("  <script src=\"http://code.jquery.com/ui/1.10.1/jquery-ui.js\"></script>\n");
      out.write("<script>\n");
      out.write("  $(function() {\n");
      out.write("       $( \"#calendar\" ).datepicker({ minDate: -20, maxDate: \"-1D\" });\n");
      out.write("       $( \"#calendar1\" ).datepicker({ minDate: -20, maxDate: \"0\" });\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("    \n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sx_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:head
    org.apache.struts2.dojo.views.jsp.ui.HeadTag _jspx_th_sx_005fhead_005f0 = (org.apache.struts2.dojo.views.jsp.ui.HeadTag) _005fjspx_005ftagPool_005fsx_005fhead_005fnobody.get(org.apache.struts2.dojo.views.jsp.ui.HeadTag.class);
    _jspx_th_sx_005fhead_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sx_005fhead_005f0.setParent(null);
    int _jspx_eval_sx_005fhead_005f0 = _jspx_th_sx_005fhead_005f0.doStartTag();
    if (_jspx_th_sx_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsx_005fhead_005fnobody.reuse(_jspx_th_sx_005fhead_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsx_005fhead_005fnobody.reuse(_jspx_th_sx_005fhead_005f0);
    return false;
  }

  private boolean _jspx_meth_sx_005fautocompleter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sx:autocompleter
    org.apache.struts2.dojo.views.jsp.ui.AutocompleterTag _jspx_th_sx_005fautocompleter_005f0 = (org.apache.struts2.dojo.views.jsp.ui.AutocompleterTag) _005fjspx_005ftagPool_005fsx_005fautocompleter_0026_005fshowDownArrow_005fname_005flist_005fid_005fcssStyle_005fnobody.get(org.apache.struts2.dojo.views.jsp.ui.AutocompleterTag.class);
    _jspx_th_sx_005fautocompleter_005f0.setPageContext(_jspx_page_context);
    _jspx_th_sx_005fautocompleter_005f0.setParent(null);
    // /manager2.jsp(29,14) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sx_005fautocompleter_005f0.setId("name");
    // /manager2.jsp(29,14) name = list type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sx_005fautocompleter_005f0.setList("complainersList");
    // /manager2.jsp(29,14) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sx_005fautocompleter_005f0.setName("customerName");
    // /manager2.jsp(29,14) name = showDownArrow type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sx_005fautocompleter_005f0.setShowDownArrow("false");
    // /manager2.jsp(29,14) name = cssStyle type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_sx_005fautocompleter_005f0.setCssStyle("width:100%;position:absolute;top:-10px;");
    int _jspx_eval_sx_005fautocompleter_005f0 = _jspx_th_sx_005fautocompleter_005f0.doStartTag();
    if (_jspx_th_sx_005fautocompleter_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsx_005fautocompleter_0026_005fshowDownArrow_005fname_005flist_005fid_005fcssStyle_005fnobody.reuse(_jspx_th_sx_005fautocompleter_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsx_005fautocompleter_0026_005fshowDownArrow_005fname_005flist_005fid_005fcssStyle_005fnobody.reuse(_jspx_th_sx_005fautocompleter_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /manager2.jsp(53,50) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("#session.email");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }
}
